[folder]
"requirements.txt" = ""
"setup.py" = """from setuptools import setup, find_packages
setup(
    name= "{{ name }}",
    version= "{{ ver }}",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
       {{ requires }} 
    ],
    )"""
  [folder.resource]
  
